name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ build-essential

      - name: Install system dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install gcc

      - name: Install system dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install mingw --version=12.2.0.0 -y

      - name: Cache Kotlin Native compiler
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.kts') }}
          restore-keys: ${{ runner.os }}-konan-

      - name: Verify Gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      
      - name: Make gradlew executable (Unix)
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew

      - name: Build and test JVM
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            ./gradlew.bat jvmTest
          else
            ./gradlew jvmTest
          fi
        shell: bash

      - name: Build and test Native
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            ./gradlew.bat nativeTest
          else
            ./gradlew nativeTest
          fi
        shell: bash
        
      - name: Complete build process
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            ./gradlew.bat build --no-daemon
          else
            ./gradlew build --no-daemon
          fi
        shell: bash

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}
          path: |
            **/build/reports/tests/
            **/build/test-results/
          retention-days: 7